apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: __SERVICE_NAME__-dbmigration-tst-01
  namespace: flux-config
spec:
  imageRepositoryRef:
    name: __SERVICE_NAME__-dbmigration
  policy:
    semver:
      range: '>=0.1.0'