apiVersion: batch/v1
kind: Job
metadata:
  name: __SERVICE_NAME__-dbmigration
  namespace: __PROGRAMME_NAME__
  labels:
    azure.workload.identity/use: "true"
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${SERVICE_NAME}
      restartPolicy: Never
      containers:
      - name: __SERVICE_NAME__-dbmigration
        imagePullPolicy: Always