apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: __SERVICE_NAME__
  namespace: flux-config
spec:
  chart:
    spec:
      version: "0.1.0" # {"$imagepolicy": "flux-config:__SERVICE_NAME__-__ENVIRONMENT__-0__ENV_INSTANCE__:tag"}
  values:
    environment: production
    name: __SERVICE_NAME__
    namespace: __TEAM_NAME__
    image: __ENVIRONMENT__adpinfcr__ENV_INSTANCE__401.azurecr.io/image/__SERVICE_NAME__:0.1.0 # {"$imagepolicy": "flux-config:__SERVICE_NAME__-__ENVIRONMENT__-0__ENV_INSTANCE__"}
    serviceAccount:
      name: __SERVICE_NAME__
    deployment:
      priorityClassName: default
    container:
      imagePullPolicy: Always
      requestMemory: 50Mi
      requestCpu: 50m
      limitMemory: 200Mi
      limitCpu: 400m
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
