apiVersion: batch/v1
kind: Job
metadata:
  name: __SERVICE_NAME__-dbmigration
  namespace: __TEAM_NAME__
  labels:
    azure.workload.identity/use: "true"
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        backstage.io/kubernetes-id: __SERVICE_NAME__
        backstage.io/kubernetes-team: __TEAM_NAME__
    spec:
      serviceAccountName: ${TEAM_NAMESPACE}
      restartPolicy: Never
      containers:
      - name: __SERVICE_NAME__-dbmigration
        imagePullPolicy: Always
