name: 1.0.$(BuildID)-${{ parameters.deployResources }}

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "All"
    values:
      - All
      - Shared Event Hub
      - FluxNotificationApi - All
      - FluxNotificationApi - MI
      - AdoCallbackApi - All
      - AdoCallbackApi - MI

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/env-shared/flux-notification-apis/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/env-shared/flux-notification-apis/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

variables:
  - name: IsAll
    value: ${{ eq(parameters.deployResources,'All') }}
  - name: IsPlatformEventHub
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'Shared Event Hub')) }}

  - name: IsFluxNotificationApi
    value: ${{ or(eq(variables.IsAll,true), startsWith(parameters.deployResources,'FluxNotificationApi')) }}  
  - name: IsFluxNotificationApiAll
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'FluxNotificationApi - All')) }}  
  - name: IsFluxNotificationApiMI
    value: ${{ or(eq(variables.IsFluxNotificationApiAll,true), eq(parameters.deployResources,'FluxNotificationApi - MI')) }}     

  - name: IsAdoCallbackApi
    value: ${{ or(eq(variables.IsAll,true), startsWith(parameters.deployResources,'AdoCallbackApi')) }}  
  - name: IsAdoCallbackApiAll
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'AdoCallbackApi - All')) }}  
  - name: IsAdoCallbackApiMI
    value: ${{ or(eq(variables.IsFluxNotificationApiAll,true), eq(parameters.deployResources,'AdoCallbackApi - MI')) }}    

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'ssv_dev'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv_tst'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - '*'           #change it to main after end to end testing
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv_pre'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'    
      - name: 'ssv_prd'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'  
    groupedDeployments:
      - ${{ if eq(variables.IsPlatformEventHub, true) }}:
        - name: SharedEventHub
          deployments:                 
            - name: event-hub
              path: infra/core/env-shared/flux-notification-apis/event-hub
              resourceGroupName: $(ssvSharedResourceGroup)

      - ${{ if eq(variables.IsFluxNotificationApi, true) }}:
          - name: FluxNotificationApi
            deployments:
              - ${{ if eq(variables.IsFluxNotificationApiMI, true) }}:                     
                - name: fluxnotificationapp-managed-identity
                  path: infra/core/env-shared/flux-notification-apis/managed-identity
                  resourceGroupName: $(ssvInfraResourceGroup)        

      - ${{ if eq(variables.IsAdoCallbackApi, true) }}:
          - name: AdoCallbackApi
            deployments:
              - ${{ if eq(variables.IsAdoCallbackApiMI, true) }}:                     
                - name: adocallbackapp-managed-identity
                  path: infra/core/env-shared/flux-notification-apis/managed-identity
                  resourceGroupName: $(ssvInfraResourceGroup)                  