trigger: none

pr: none

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

extends:
  template: /pipelines/common-script-deploy.yaml@ADPPipelineCommon
  parameters:
    environments:
      - name: 'snd1'
        serviceConnection: AZD-CDO-SND1
        deploymentBranches:
          - '*'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'snd2'
        serviceConnection: AZD-CDO-SND2
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
    keyVaultName: $(ssvPlatformKeyVaultName)
    scriptsList:
      - displayName: Link the Private DNS Zone to Central networks
        scriptPath: /scripts/ado/Trigger-LinkPrivateDNSZones.ps1
        type: PowerShell
        useSystemAccessToken: true
        scriptArguments: >
          -privateDnsZoneName "$(dnsResourceNamePrefix)$(nc_resource_dnszone)$(nc_instance_regionid)01.privatelink.uksouth.azmk8s.io"
          -resourceGroupName $(aksResourceGroup)
          -subscriptionName $(subscriptionName)
          -tenantId $(tenantId)