name: 1.0.$(BuildID)-${{ parameters.deployResources }}

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "All"
    values:
      - All
      - Cluster Custom Resources Reader Role
      - Cluster Port Forward User Role
pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/iam/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/iam/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA-ADP
      type: github
      ref: main
      
variables:
  - name: IsAll
    value: ${{ eq(parameters.deployResources,'All') }}
  - name: IsClusterCustomResourcesReaderRole
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'Cluster Custom Resources Reader Role')) }}
  - name: IsClusterPortForwardUserRole
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'Cluster Port Forward User Role')) }}

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    variableFiles: 
      - /pipelines/vars/common.yaml@_self
      - /pipelines/vars/env/{environment}.yaml@_self
    filePathsForTransform: |
      **/infra/core/iam/subscription/aad-groups/clusteraccessgroup.json
    groupedDeployments:
        - name: role_assignments
          deployments:
           - ${{ if eq(variables.IsClusterCustomResourcesReaderRole, true) }}:
              - name: Create or Update AAD groups
                type: 'script'
                scriptType: AzurePowerShell
                serviceConnectionVariableName: ssvServiceConnection
                scriptRepo: 'PipelineCommonScripts'
                path: 'PowerShellLibrary/Create-AADGroups.ps1'
                scriptArguments: > 
                  -AADGroupsJsonManifestPath '$(Pipeline.Workspace)/s/self/infra/core/iam/subscription/aad-groups/clusteraccessgroup.json'
              - name: cluster-custom-resources-reader-role
                path: infra/core/iam/subscription
                scope: "Subscription"
                preDeployScriptsList:
                - displayName: 'Get Group Id'
                  type: AzurePowerShell
                  serviceConnectionVariableName: ssvServiceConnection
                  inlineScript: |
                    $groupId = (Get-AzADGroup -DisplayName '$(customRoleCustomResourcesReaderGroup)').id
                    Write-Host "##vso[task.setvariable variable=customRoleCustomResourcesReaderGroupId;]$groupId"
                - displayName: 'Get Portal App PrincipalId'
                  type: AzurePowerShell
                  serviceConnectionVariableName: 'subscriptionName'
                  inlineScript: |
                    $roleid = (Get-AzRoleDefinition -Name '$(customRoleCustomResourcesReader)').Id
                    $ObjectId = (Get-AzADServicePrincipal -DisplayName '$(portalAppRegName)').Id
                    Write-Host "##vso[task.setvariable variable=customRoleCustomResourcesReaderRoleId;]$roleid"
                    Write-Host "##vso[task.setvariable variable=portalAppPrincipalId;]$ObjectId"
           - ${{ if eq(variables.IsClusterPortForwardUserRole, true) }}:
              - name: cluster-port-forward-user-role
                path: infra/core/iam/subscription/port-forward
                scope: "Subscription"
                preDeployScriptsList:
                - displayName: 'Get Group Id'
                  type: AzurePowerShell
                  serviceConnectionVariableName: ssvServiceConnection
                  inlineScript: |
                    $groupId = (Get-AzADGroup -DisplayName '$(customRoleCustomResourcesReaderGroup)').id
                    Write-Host "##vso[task.setvariable variable=customRolePortForwardUserGroupId;]$groupId"
                - displayName: 'Get Role ID'
                  type: AzurePowerShell
                  serviceConnectionVariableName: 'subscriptionName'
                  inlineScript: |
                    $roleid = (Get-AzRoleDefinition -Name '$(customRolePortForwardUser)').Id
                    Write-Host "##vso[task.setvariable variable=customRolePortForwardUserRoleId;]$roleid"