parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "all"
    values:
      - "all"
      - "network"
      - "portal-app"
      - "portal-app-sa"
      - "portal-app-kv"
      - "portal-app-mi"
      - "portal-app-db"
      - "portal-app-env"      

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/env-shared/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/env-shared/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref:  refs/heads/rv/249199-deploymentfix

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}  
    environments:
      - name: 'ssv3'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        privateAgentName: 'DEFRA-COMMON-ubuntu2204-SSV3'
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv5'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-COMMON-ubuntu2004-SSV5'
        azureRegions:
          primary: 'UKSouth'  
    filePathsForTransform: |
      **/core/env-shared/portal/app-registrations/portal-app-registration.json  
    groupedDeployments:                
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'network')) }}        
        : - name: network 
            deployments:
              - name: route-table
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: network-security-group
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: virtual-network
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
                postDeployScriptsList:
                  - displayName: Link the VNet to Hub
                    scriptPath: infra/bootstrap/env/scripts/Trigger-VNetPeering.ps1
                    type: PowerShell
                    useSystemAccessToken: true
                    scriptArguments: >
                      -VirtualNetworkName $(ssvVirtualNetworkName)
                      -SubscriptionName $(subscriptionName)
                      -TenantId $(tenantId)
      - ? ${{ if or(eq(parameters.deployResources, 'all'), contains(parameters.deployResources, 'portal-app')) }}        
        : - name: Portal
            ${{ if eq(parameters.deployResources, 'all') }}:
              dependsOnGroupedDeployments:
                - network        
            deployments:
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-kv')) }}:
                - name: key-vault
                  path: infra/core/env-shared/portal/key-vault
                  resourceGroupName: $(portalResourceGroup)
                  privateEndpointDnsRecordsForResources:
                    - resourceName: $(ssvResourceNamePrefix)$(nc_resource_keyvault)$(nc_instance_regionid)02
                      resourceGroupName: $(portalResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-sa')) }}:
                - name: storage-account
                  path: infra/core/env-shared/portal/storage-account
                  resourceGroupName: $(portalResourceGroup)
                  privateEndpointDnsRecordsForResources:
                    - resourceName: $(ssvResourceNamePrefix)$(nc_resource_storageaccount)$(nc_instance_regionid)01
                      resourceGroupName: $(portalResourceGroup)                      
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-mi')) }}:
                - name: managed-identity
                  path: infra/core/env-shared/portal/managed-identity
                  resourceGroupName: $(portalResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-db')) }}:
                - name: flexible-server-zone
                  path: infra/core/env-shared/portal/flexible-server-zone
                  resourceGroupName: $(dnsResourceGroup)
                  postDeployScriptsList:
                    - displayName: Link the Private DNS Zone to Central networks
                      scriptPath: infra/core/env/scripts/Trigger-LinkPrivateDNSZones.ps1
                      type: PowerShell
                      useSystemAccessToken: true
                      scriptArguments: >
                        -PrivateDnsZoneName "$(dnsResourceNamePrefix)$(nc_resource_dnszone)$(nc_instance_regionid)01.private.postgres.database.azure.com"
                        -ResourceGroupName $(dnsResourceGroup)
                        -SubscriptionName $(subscriptionName)
                        -TenantId $(tenantId)
                - name: flexible-server
                  path: infra/core/env-shared/portal/flexible-server
                  resourceGroupName: $(portalResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-env')) }}:
                - name: container-apps-env
                  path: infra/core/env-shared/portal/container-apps-env
                  resourceGroupName: $(portalResourceGroup)
                  postDeployScriptsList:
                  - displayName: 'Process Output Variable'
                    type: PowerShell
                    inlineScript: |
                      $output = '$(azureDeploymentOutputs)' | ConvertFrom-Json
                      Write-Host "##vso[task.setvariable variable=portalAppUrl;]$($output.appUrl.value)"
                      $filePath = "$(Pipeline.Workspace)/s/self/infra/core/env-shared/portal/app-registrations/portal-app-registration.json"                                           
                      (Get-Content $filePath) -replace "{{portalAppUrl}}", "$($output.appUrl.value)" | Set-Content $filePath     
                  - displayName: Register App
                    scriptPath: "PowerShellLibrary/Add-AdAppRegistrations.ps1"
                    scriptRepo: PipelineCommonScripts
                    ScriptArguments: >
                      -AppRegJsonPath '$(Pipeline.Workspace)/s/self/infra/core/env-shared/portal/app-registrations/portal-app-registration.json'
