parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false

pr:
  branches:
    include:
    - main
  paths:
    include:
    - infra/*
    - scripts/*
    exclude:
    - infra/config/app-registrations/*
    - infra/config/service-connections/*
    - scripts/service-connection/*
    - scripts/Assign-RBAC-Subscription.ps1

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
    - infra/*
    - scripts/*
    exclude:
    - infra/config/app-registrations/*
    - infra/config/service-connections/*
    - scripts/service-connection/*
    - scripts/Assign-RBAC-Subscription.ps1

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'snd2'
        serviceConnection: AZD-CDO-SND2
        deploymentBranches:
          - '*'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
    groupedTemplates:      
      - name: front_door
        templates:
          - name: front-door
            path: infra/front-door
            resourceGroupName: $(frontDoorResourceGroup)
          - name: front-door-waf
            path: infra/front-door
            resourceGroupName: $(frontDoorResourceGroup)                 