name: 1.0.$(BuildID)-${{ parameters.deployResources }}

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "All"
    values:
      - All
      - Shared Event Hub
      - FluxNotificationApps - Manage Identites
      - FluxNotificationApps - Storage Account

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/env-shared/flux-notification-apis/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/env-shared/flux-notification-apis/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

variables:
  - name: IsAll
    value: ${{ eq(parameters.deployResources,'All') }}
  - name: IsPlatformEventHub
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'Shared Event Hub')) }}

  - name: IsFluxNotificationAppsMI
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'FluxNotificationApps - Manage Identites')) }}

  - name: IsFluxNotificationStorageAccount
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'FluxNotificationApps - Storage Account')) }}

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'ssv_dev'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv_tst'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - '*'           #change it to main after end to end testing
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv_pre'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'    
      - name: 'ssv_prd'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'  
    groupedDeployments:
      - ${{ if eq(variables.IsPlatformEventHub, true) }}:
        - name: SharedEventHub
          deployments:                 
            - name: event-hub
              path: infra/core/env-shared/flux-notification-apis/event-hub
              resourceGroupName: $(ssvSharedResourceGroup)

      - ${{ if eq(variables.IsFluxNotificationStorageAccount, true) }}:
          - name: FluxNotificationStorageAccount
            deployments:                    
              - name: storage-account
                path: infra/core/env-shared/flux-notification-apis/storage-account
                resourceGroupName: $(ssvInfraResourceGroup)
                privateEndpointDnsRecordsForResources:
                  - resourceName: $(fluxNotificationStorageAccountName)
                    resourceGroupName: $(ssvInfraResourceGroup) 
              
      - ${{ if eq(variables.IsFluxNotificationAppsMI, true) }}:
          - name: FluxNotificationAppsManageIdentities
            deployments:                    
              - name: fluxnotificationapp-managed-identity
                path: infra/core/env-shared/flux-notification-apis/managed-identity
                resourceGroupName: $(ssvInfraResourceGroup)  
              - name: adocallbackapp-managed-identity
                path: infra/core/env-shared/flux-notification-apis/managed-identity
                resourceGroupName: $(ssvInfraResourceGroup)                           
                                