parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: imageType
    displayName: 'Select Image Type for the agent'
    type: string
    default: ubuntu2204
    values:
      - ubuntu2004
      - ubuntu2204

pr:
  branches:
    include:
    - main
  paths:
    include:
    - infra/vmss/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
    - infra/vmss/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

variables:
  imageType: ${{ parameters.imageType }}

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'snd1'
        serviceConnection: AZD-CDO-SND1-VMSS
        deploymentBranches:
          - '*'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
    groupedTemplates:
      - name: build_agent
        templates:
          - name: build-agent
            path: infra/vmss
            resourceGroupName: $(servicesResourceGroup)