parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "all"
    values:
      - "all"
      - "network"
      - "portal-app"
      - "portal-app-sa"
      - "portal-app-kv"
      - "portal-app-mi"
      - "portal-app-db"
      - "portal-app-env"
      - "portal-api-mi"    

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/env-shared/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/env-shared/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref:  refs/heads/sm/304334-ContainerAppsImprovement 

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}  
    environments:
      # - name: 'ssv_dev'
      #   serviceConnection: AZD-ADP-SSV3
      #   deploymentBranches:
      #     - 'refs/heads/main'          
      #   developmentEnvironment: true
      #   privateAgentName: 'DEFRA-COMMON-ubuntu2204-SSV3'
      #   azureRegions:
      #     primary: 'UKSouth'    
      - name: 'ssv_tst'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - '*'          
        developmentEnvironment: true
        privateAgentName: 'DEFRA-COMMON-ubuntu2204-SSV3'
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv_pre'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-COMMON-ubuntu2004-SSV5'
        azureRegions:
          primary: 'UKSouth'  
      - name: 'ssv_prd'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-COMMON-ubuntu2004-SSV5'
        azureRegions:
          primary: 'UKSouth'            
    filePathsForTransform: |
      **/core/env-shared/portal/app-registrations/portal-app-registration.json  
    groupedDeployments:                
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'network')) }}        
        : - name: network 
            deployments:
              - name: route-table
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: network-security-group
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: virtual-network
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
                postDeployScriptsList:
                  - displayName: Link the VNet to Hub
                    scriptPath: infra/bootstrap/env/scripts/Trigger-VNetPeering.ps1
                    type: PowerShell
                    useSystemAccessToken: true
                    scriptArguments: >
                      -VirtualNetworkName $(ssvVirtualNetworkName)
                      -SubscriptionName $(subscriptionName)
                      -TenantId $(tenantId)
      - ${{ if or(eq(parameters.deployResources, 'all'), contains(parameters.deployResources, 'portal-app')) }} :
          - name: Portal
            ${{ if eq(parameters.deployResources, 'all') }}:
              dependsOnGroupedDeployments:
                - network        
            deployments:
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-kv')) }}:
                - name: key-vault
                  path: infra/core/env-shared/portal/key-vault
                  resourceGroupName: $(ssvInfraResourceGroup)
                  privateEndpointDnsRecordsForResources:
                    - resourceName: $(ssvInfraKeyVault)
                      resourceGroupName: $(ssvInfraResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-sa')) }}:
                - name: storage-account
                  path: infra/core/env-shared/portal/storage-account
                  resourceGroupName: $(ssvInfraResourceGroup)
                  privateEndpointDnsRecordsForResources:
                    - resourceName: $(portalStorageAccountName)
                      resourceGroupName: $(ssvInfraResourceGroup)                      
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-mi')) }}:
                - name: managed-identity
                  path: infra/core/env-shared/portal/managed-identity
                  resourceGroupName: $(ssvInfraResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-db')) }}:
                - name: flexible-server-zone
                  path: infra/core/env-shared/portal/flexible-server-zone
                  resourceGroupName: $(dnsResourceGroup)
                  postDeployScriptsList:
                    - displayName: Link the Private DNS Zone to Central networks
                      scriptPath: infra/core/env/scripts/Trigger-LinkPrivateDNSZones.ps1
                      type: PowerShell
                      useSystemAccessToken: true
                      scriptArguments: >
                        -PrivateDnsZoneName "$(postgreSqlPvtDnsZone)"
                        -ResourceGroupName $(dnsResourceGroup)
                        -SubscriptionName $(subscriptionName)
                        -TenantId $(tenantId)
                - name: flexible-server
                  path: infra/core/env-shared/portal/flexible-server
                  resourceGroupName: $(ssvInfraResourceGroup)               
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-app'), eq(parameters.deployResources, 'portal-app-env')) }}:
                - name: container-apps-env
                  path: infra/core/env-shared/portal/container-apps-env
                  resourceGroupName: $(ssvInfraResourceGroup)
                  postDeployScriptsList:  
                  - displayName: 'Process Output Variable'
                    type: PowerShell
                    inlineScript: |
                      $output = '$(azureDeploymentOutputs)' | ConvertFrom-Json
                      Write-Host "##vso[task.setvariable variable=containerAppEnvPvtDnsZone;]$($output.defaultDomain.value)"  
                  - displayName: Register App
                    scriptPath: "PowerShellLibrary/Add-AdAppRegistrations.ps1"
                    scriptRepo: PipelineCommonScripts
                    ScriptArguments: >
                      -AppRegJsonPath '$(Pipeline.Workspace)/s/self/infra/core/env-shared/portal/app-registrations/portal-app-registration.json'
                - name: containerapp-dns-zone
                  path: infra/core/env-shared/portal/containerapp-dns-zone
                  resourceGroupName: $(dnsResourceGroup)
                  postDeployScriptsList:
                    - displayName: Link the Private DNS Zone to Central networks
                      scriptPath: infra/core/env/scripts/Trigger-LinkPrivateDNSZones.ps1
                      type: PowerShell
                      useSystemAccessToken: true
                      scriptArguments: >
                        -PrivateDnsZoneName "$(containerAppEnvPvtDnsZone)"
                        -ResourceGroupName $(dnsResourceGroup)
                        -SubscriptionName $(subscriptionName)
                        -TenantId $(tenantId)                          
                       
      - ${{ if or(eq(parameters.deployResources, 'all'), contains(parameters.deployResources, 'portal-api')) }} :
          - name: PortalAPI
            deployments:
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal-api-mi')) }}:
                - name: managed-identity
                  path: infra/core/env-shared/portal-api/managed-identity
                  resourceGroupName: $(ssvInfraResourceGroup)                          
