name: 1.0.$(BuildID)-${{ parameters.deployResources }}

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "All"
    values:
      - All

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/tenant/*
      - infra/common/*
trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/tenant/*
      - infra/common/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: pp/defra-test
      
variables:
  - name: IsAll
    value: ${{ eq(parameters.deployResources,'All') }}

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    variableFiles: 
      - /pipelines/vars/common.yaml@_self
      - /pipelines/vars/tenant/{environment}.yaml@_self
    regionalVariableFiles: []
    environments:
      - name: 'defradev'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
          - 'refs/pull/*/merge'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'defra_non_prd'
        outputTemplateChange: Skip
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
           - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'    
      - name: 'defra'
        outputTemplateChange: Skip
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
           - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'    
    groupedDeployments:
          - name: role_definitions
            deployments:
              - name: servicebus-customrole
                path: infra/core/tenant/role-definitions
