name: 1.0.$(BuildID)-${{ parameters.deployResources }}

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "All"
    values:
      - All
      - Cluster Custom Resources Reader Role
pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/iam/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - infra/core/iam/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: rv/372068
      
variables:
  - name: IsAll
    value: ${{ eq(parameters.deployResources,'All') }}
  - name: IsClusterCustomResourcesReaderRole
    value: ${{ or(eq(variables.IsAll,true), eq(parameters.deployResources,'Cluster Custom Resources Reader Role')) }}    

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    variableFiles: 
      - /pipelines/vars/common.yaml@_self
      - /pipelines/vars/env/{environment}.yaml@_self
    environments:
      - name: 'snd1'
        serviceConnection: AZD-ADP-SND1
        deploymentBranches:
          - 'refs/heads/rv/372068'
        developmentEnvironment: true
        privateAgentName: 'DEFRA-ADP-SND1-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'
      - name: 'snd2'
        serviceConnection: AZD-ADP-SND2
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-ADP-SND2-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'          
      - name: 'snd3'
        serviceConnection: AZD-ADP-SND3
        deploymentBranches:
          - 'refs/heads/main'
          - 'refs/pull/*/merge'
        privateAgentName: 'DEFRA-ADP-SND3-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'      
      - name: tst1
        serviceConnection: AZR-ADP-TST1
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-ADP-TST1-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'              
      - name: pre1
        serviceConnection: AZR-ADP-PRE1
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-ADP-PRE1-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'
      - name: prd1
        serviceConnection: AZR-ADP-PRD1
        deploymentBranches:
          - 'refs/heads/main'
        privateAgentName: 'DEFRA-ADP-PRD1-ubuntu2204'
        azureRegions:
          primary: 'UKSouth'   
    groupedDeployments:
        - name: role_assignments
          deployments:
           - ${{ if eq(variables.IsClusterCustomResourcesReaderRole, true) }}:
              - name: cluster-custom-resources-reader-role
                path: infra/core/iam/subscription
                scope: "Subscription"
                preDeployScriptsList:  
                - displayName: 'Get Portal App PrincipalId'
                  type: AzurePowerShell
                  serviceConnectionVariableName: 'subscriptionName'
                  inlineScript: |
                    $roleid = (Get-AzRoleDefinition -Name '$(customRoleCustomResourcesReader)').Id
                    Get-AzADServicePrincipal -DisplayName '$(portalAppRegName)'
                    $AppId = (Get-AzADServicePrincipal -DisplayName '$(portalAppRegName)').AppId
                    Write-Host "##vso[task.setvariable variable=customRoleCustomResourcesReaderRoleId;]$roleid"                    
                    Write-Host "##vso[task.setvariable variable=portalAppPrincipalId;]$AppId"