parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "all"
    values:
      - "all"
      - "shared"
      - "network"
      - "portal"
      - "portal-container-apps-env"

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/core/env-shared/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - 'none'
  paths:
    include:
      - infra/core/env-shared/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref:  refs/heads/rv/263292-backstageportal2

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}  
    environments:
      - name: 'ssv3'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv5'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'    
    groupedDeployments:
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'shared')) }}        
        : - name: SharedResources 
            deployments:
              - name: platform-container-registry
                path: infra/core/env-shared/container-registry
                resourceGroupName: $(ssvSharedResourceGroup)
              - name: log-analytics-workspace
                path: infra/core/env-shared/log-analytics-workspace
                resourceGroupName: $(ssvSharedResourceGroup)
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'network')) }}        
        : - name: network 
            deployments:
              - name: route-table
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: network-security-group
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: virtual-network
                path: infra/core/env-shared/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
                postDeployScriptsList:
                  - displayName: Link the VNet to Hub
                    scriptPath: infra/bootstrap/env/scripts/Trigger-VNetPeering.ps1
                    type: PowerShell
                    useSystemAccessToken: true
                    scriptArguments: >
                      -VirtualNetworkName $(ssvVirtualNetworkName)
                      -SubscriptionName $(subscriptionName)
                      -TenantId $(tenantId)
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal'), eq(parameters.deployResources, 'portal-container-apps-env')) }}        
        : - name: Portal
            ${{ if eq(parameters.deployResources, 'all') }}:
              dependsOnGroupedDeployments:
                - SharedResources        
            deployments:
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal')) }}:
                - name: key-vault
                  path: infra/core/env-shared/portal/key-vault
                  resourceGroupName: $(portalResourceGroup)
                - name: managed-identity
                  path: infra/core/env-shared/portal/managed-identity
                  resourceGroupName: $(portalResourceGroup)
                - name: flexible-server-zone
                  path: infra/core/env-shared/portal/flexible-server-zone
                  resourceGroupName: $(dnsResourceGroup)
                  postDeployScriptsList:
                    - displayName: Link the Private DNS Zone to Central networks
                      scriptPath: infra/core/env/scripts/Trigger-LinkPrivateDNSZones.ps1
                      type: PowerShell
                      useSystemAccessToken: true
                      scriptArguments: >
                        -PrivateDnsZoneName "$(dnsResourceNamePrefix)$(nc_resource_dnszone)$(nc_instance_regionid)03.private.postgres.database.azure.com"
                        -ResourceGroupName $(dnsResourceGroup)
                        -SubscriptionName $(subscriptionName)
                        -TenantId $(tenantId)
                - name: flexible-server
                  path: infra/core/env-shared/portal/flexible-server
                  resourceGroupName: $(portalResourceGroup)
              - ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal'), eq(parameters.deployResources, 'portal-container-apps-env')) }}:
                - name: container-apps-env
                  path: infra/core/env-shared/portal/container-apps-env
                  resourceGroupName: $(portalResourceGroup)
