parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false

trigger: none

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: pp/refactor

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'snd2'
        serviceConnection: AZD-CDO-SND2
        deploymentBranches:
          - '*'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
    groupedTemplates:
      - name: monitoring
        templates:
          - name: workspace
            path: infra/operational-insights
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
          - name: component
            path: infra/insights
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
      - name: security
        dependsOnGroupedTemplates:
          - monitoring
        templates:
          - name: application-key-vault
            path: infra/key-vault
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
            privateEndpointDnsRecordsForResources:
              - resourceName: $(infraResourceNamePrefix)$(nc_resource_keyvault)$(nc_instance_regionid)01 
                resourceGroupName: $(servicesResourceGroup)
      - name: managed_cluster
        templates:
          - name: aks-cluster
            path: infra/managed-cluster
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
      - name: service_bus
        templates:
          - name: namespace
            path: infra/service-bus
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for $(infraResourceNamePrefix)$(nc_resource_servicebus)$(nc_instance_regionid)01
                scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                ScriptArguments: >
                  -ResourceGroupName $(servicesResourceGroup)
                  -ResourceName $(infraResourceNamePrefix)$(nc_resource_servicebus)$(nc_instance_regionid)01                 
              - displayName: Set DNS record for $(infraResourceNamePrefix)$(nc_resource_servicebus)$(nc_instance_regionid)01
                scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                serviceConnectionVariableName: mstAzureResourceManagerConnection
      - name: app_configuration
        templates:
          - name: configuration-store
            path: infra/app-configuration
            type: bicep
            scope: "Resource Group"
            acrServiceConnection: $(acrServiceConnection)
            resourceGroupName: $(servicesResourceGroup)
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for $(infraResourceNamePrefix)$(nc_resource_appconfiguration)$(nc_instance_regionid)01
                scriptPath: 'Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon'
                ScriptArguments: >
                  -ResourceGroupName $(servicesResourceGroup)
                  -ResourceName $(infraResourceNamePrefix)$(nc_resource_appconfiguration)$(nc_instance_regionid)01                 
              - displayName: Set DNS record for $(infraResourceNamePrefix)$(nc_resource_appconfiguration)$(nc_instance_regionid)01
                scriptPath: 'Set-PrivateDnsRecordSet.ps1@PipelineCommon'
                serviceConnectionVariableName: mstAzureResourceManagerConnection