parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployResources
    displayName: "Resources to Deploy"
    type: string
    default: "all"
    values:
      - "all"
      - "shared"
      - "network"
      - "portal"

pr:
  branches:
    include:
    - main
  paths:
    include:
      - infra/core-shared-services/*

trigger:
  batch: true
  branches:
    include:
      - 'none'
  paths:
    include:
      - infra/core-shared-services/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref:  refs/heads/rv/263292-backstageportal

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}  
    environments:
      - name: 'ssv3'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
    groupedDeployments:
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'shared')) }}        
        : - name: SharedResources 
            deployments:
              - name: platform-container-registry
                path: infra/core-shared-services/container-registry
                resourceGroupName: $(ssvSharedResourceGroup)
              - name: log-analytics-workspace
                path: infra/core-shared-services/log-analytics-workspace
                resourceGroupName: $(ssvSharedResourceGroup)
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'network')) }}        
        : - name: network 
            deployments:
              - name: route-table
                path: infra/core-shared-services/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: network-security-group
                path: infra/core-shared-services/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
              - name: virtual-network
                path: infra/core-shared-services/network
                serviceConnectionVariableName: "subscriptionName"
                resourceGroupName: $(ssvVirtualNetworkResourceGroup)
                postDeployScriptsList:
                  - displayName: Link the VNet to Hub
                    scriptPath: infra/bootstrap/scripts/Trigger-VNetPeering.ps1
                    type: PowerShell
                    useSystemAccessToken: true
                    scriptArguments: >
                      -VirtualNetworkName $(ssvVirtualNetworkName)
                      -SubscriptionName $(subscriptionName)
                      -TenantId $(tenantId)
      - ? ${{ if or(eq(parameters.deployResources, 'all'), eq(parameters.deployResources, 'portal')) }}        
        : - name: Portal
            ${{ if eq(parameters.deployResources, 'all') }}:
              dependsOnGroupedDeployments:
                - SharedResources        
            deployments:
              - name: key-vault
                path: infra/core-shared-services/portal/key-vault
                resourceGroupName: $(portalResourceGroup)
              - name: managed-identity
                path: infra/core-shared-services/portal/managed-identity
                resourceGroupName: $(portalResourceGroup)
              - name: flexible-server-zone
                path: infra/core-shared-services/portal/flexible-server-zone
                resourceGroupName: $(portalResourceGroup)
              - name: flexible-server
                path: infra/core-shared-services/portal/flexible-server
                resourceGroupName: $(portalResourceGroup)
              - name: container-apps-env
                path: infra/core-shared-services/portal/container-apps-env
                resourceGroupName: $(portalResourceGroup)

