parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: imageType
    displayName: 'Select Image Type for the agent'
    type: string
    default: ubuntu2204
    values:
      - windows2022
      - ubuntu2204
      - windows2019
      - ubuntu2004

pr:
  branches:
    include:
    - main
  paths:
    include:
    - infra/vmss/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
    - infra/vmss/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: features/script-deployment

variables:
  imageType: ${{ parameters.imageType }}
  ${{ if eq(parameters.imageType, 'windows2022') }}:
    instanceNumber: 01
  ${{ if eq(parameters.imageType, 'ubuntu2204') }}:
    instanceNumber: 02
  ${{ if eq(parameters.imageType, 'windows2019') }}:
    instanceNumber: 03
  ${{ if eq(parameters.imageType, 'ubuntu2004') }}:
    instanceNumber: 04
  

extends:
  template: /pipelines/common-script-deploy.yaml@ADPPipelineCommon
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'snd1'
        serviceConnection: AZD-CDO-SSV3
        deploymentBranches:
          - '*'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
    keyVaultName: ${{ variables.ssvPlatformKeyVaultName }}
    scriptsList:
      - displayName: Deploy Build Agent - ${{ parameters.imageType }}
        scriptPath: /scripts/ADO-Build-Agent.ps1
        scriptArguments: >
          -imageGalleryTenant ${{ variables.imageGalleryTenant }}
          -tenantId ${{ variables.tenantId }}
          -subscriptionName ${{ variables.subscriptionName }}
          -resourceGroup ${{ variables.servicesResourceGroup }}
          -vmssName ${{ variables.infraResourceNamePrefix }}${{ variables.nc_resource_virtualmachine_scalesets }}${{ variables.nc_instance_regionid }}${{ variables.instanceNumber }}
          -imageType ${{ parameters.imageType }}
          -subnetId /subscriptions/${{ variables.subscriptionId }}/resourceGroups/${{ variables.virtualNetworkResourceGroup }}/providers/Microsoft.Network/virtualNetworks/${{ variables.virtualNetworkName }}/subnets/${{ variables.networkResourceNamePrefix }}${{ variables.nc_resource_subnet }}${{ variables.nc_instance_regionid }}03
          -imageId /subscriptions/${{ variables.imageGallerySubscription }}/resourceGroups/${{ variables.imageGalleryResourceGroup }}/providers/Microsoft.Compute/galleries/${{ variables.imageGalleryName }}/images/${{ parameters.imageType }}
          -adoAgentPassword $(ADO-BuildAgent-Password)
        type: AzureCLI
