parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: nginxVersion
    type: string
    default: 3.2.0

pr:
  branches:
    include:
    - main
  paths:
    include:
      - nginxplus/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - nginxplus/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

extends:
  template: /pipelines/common-script-deploy.yaml@ADPPipelineCommon
  parameters:
    privateAgentName: 'DEFRA-COMMON-ubuntu2204-SSV3'
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'ssv3'
        serviceConnection: AZD-ADP-SSV3
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      - name: 'ssv5'
        serviceConnection: AZR-ADP-SSV5
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
    scriptsList:
      - displayName: Publish Nginx Image to ACR
        scriptPath: 'nginxplus/Publish-NginxPlus-Acr.ps1'
        scriptArguments: >
          -AcrName $(ssvSharedAcrName)
          -AzureSubscription $(subscriptionName)
          -KeyVaultName $(ssvPlatformKeyVaultName)
          -NGINXCertSecretName $(nginxCertSecretName)
          -NGINXKeySecretName $(nginxKeySecretName)
          -NGINXVersion: ${{ parameters.nginxVersion }}
          -CertFilesPath $(Build.ArtifactStagingDirectory)
        type: AzureCLI
        azureCLIScriptType: 'pscore'