apiVersion: batch/v1
kind: Job
metadata:
  name: __SERVICE_NAME__-dbmigration
  namespace: __TEAM_NAME__
spec:
  template:
    spec:
      containers:
      - name: __SERVICE_NAME__-dbmigration
        image: __ENVIRONMENT__adpinfcr__ENV_INSTANCE__401.azurecr.io/image/__SERVICE_NAME__-dbmigration:__VERSION__ # {"$imagepolicy": "flux-config:__SERVICE_NAME__-dbmigration-__ENVIRONMENT__-0__ENV_INSTANCE__"}
        env:
        - name: POSTGRES_HOST
          value: "${SHARED_POSTGRES_SERVER_01}.postgres.database.azure.com"
        - name: SCHEMA_NAME
          value: ${POSTGRES_SCHEMA_NAME}
        - name: POSTGRES_DB
          value: ${POSTGRES_DB}
        - name: POSTGRES_PORT
          value: "${POSTGRES_PORT}"
        - name: SCHEMA_USERNAME
          value: "AAG-Azure-ADP-__SERVICE_CODE__-__ENVIRONMENT____ENV_INSTANCE__-PostgresDB_Writer"
