apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: __SERVICE_NAME__-__ENVIRONMENT__-0__ENV_INSTANCE__
  namespace: flux-config
spec:
  imageRepositoryRef:
    name: __SERVICE_NAME__
  policy:
    semver:
      range: '>=1.0.0'